### ISSUE TITLE
Metadata record for Transaction/Insert test is not DGIWG

### ISSUE THREAD

**Issue by etj** [opengeospatial/ets-cat20-dgiwg10#33] opened 2018-09-19 16:06 UTC
The test record at `src/main/resources/org/opengis/cite/cat20/dgiwg10/transaction/insert-DMFMetadata-request.xml` contains:
```
      <ns4:metadataStandardName>
        <ns2:CharacterString>ISO 19115</ns2:CharacterString>
      </ns4:metadataStandardName>
      <ns4:metadataStandardVersion>
        <ns2:CharacterString>2003/Cor.1:2006</ns2:CharacterString>
      </ns4:metadataStandardVersion>
```
so it's not recognized as a DGIWG metadata record by the catalog. 

The catalog applies different transformations according to the metadata schema.

**Comment by lgoltz** [comment] 2018-09-20 05:40
Duplicate of #30

**Closed as completed by lgoltz** 2018-09-20 05:40 UTC
Labels: duplicate
